### ISSUE TITLE
M1-3: Organization Classification System (Worker 2)

### ISSUE THREAD

**Issue by bouthilx** [bouthilx/compute-forecast-framework#44]
# M1-3: Organization Classification System Enhancement

## Objective
Enhance existing academic vs industry classification system with improved accuracy and coverage.

**Worker**: W2-Org | **Effort**: S(2-3h) | **Domain**: Infrastructure

### Enhanced Organization Classifier
```python
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple, Set
from enum import Enum
from src.analysis.classification.organizations import OrganizationClassifier
from src.analysis.classification.affiliation_parser import AffiliationParser

class OrganizationType(Enum):
    ACADEMIC = "academic"
    INDUSTRY = "industry"
    GOVERNMENT = "government"
    NON_PROFIT = "non_profit"
    UNKNOWN = "unknown"

@dataclass
class OrganizationRecord:
    name: str
    type: OrganizationType
    aliases: List[str] = None
    domains: List[str] = None  # email domains
    keywords: List[str] = None  # identifying keywords
    confidence: float = 1.0

@dataclass
class ClassificationResult:
    organization: str
    type: OrganizationType
    confidence: float
    match_method: str  # exact, alias, domain, keyword, fuzzy
    evidence: Dict[str, Any]

class EnhancedOrganizationClassifier(OrganizationClassifier):
    """Extends existing classifier with improved matching"""
    
    def __init__(self):
        super().__init__()
        self.fuzzy_threshold = 0.85
        self.industry_threshold = 0.25  # 25% industry authors
    
    def load_enhanced_database(self, yaml_path: str) -> None:
        """Load expanded organization database from YAML"""
        pass
    
    def classify_with_confidence(self, affiliation: str) -> ClassificationResult:
        """Classify with detailed confidence scoring"""
        pass
    
    def add_organization(self, org: OrganizationRecord) -> None:
        """Add new organization to database"""
        pass
    
    def classify_paper_authors(self, authors: List[Author]) -> Dict[str, Any]:
        """Classify paper based on author affiliations"""
        # Returns:
        # {
        #   "classification": "academic" or "industry",
        #   "confidence": 0.95,
        #   "academic_ratio": 0.75,
        #   "industry_ratio": 0.25,
        #   "author_breakdown": [...]
        # }
        pass
```

### Enhanced Affiliation Parser
```python
from src.analysis.classification.affiliation_parser import AffiliationParser

class EnhancedAffiliationParser(AffiliationParser):
    """Extends existing parser with better edge case handling"""
    
    def __init__(self):
        super().__init__()
        self.department_patterns = []
        self.location_patterns = []
    
    def parse_complex_affiliation(self, affiliation: str) -> Dict[str, Any]:
        """Handle complex multi-part affiliations"""
        # Input: "Dept. of CS, University of Toronto, Toronto, ON, Canada"
        # Output: {
        #   "organization": "University of Toronto",
        #   "department": "Computer Science",
        #   "city": "Toronto",
        #   "country": "Canada"
        # }
        pass
    
    def extract_primary_organization(self, parsed: Dict[str, Any]) -> str:
        """Extract main organization from parsed data"""
        pass
    
    def handle_edge_cases(self, affiliation: str) -> Optional[str]:
        """Handle known edge cases"""
        # - Multiple affiliations separated by semicolons
        # - Affiliations with both academic and industry
        # - Abbreviated organization names
        # - Non-English affiliations
        pass
```

### Database Expansion Format
```yaml
# config/organizations_enhanced.yaml
academic:
  - name: "Massachusetts Institute of Technology"
    aliases: ["MIT", "M.I.T.", "Mass. Inst. of Tech."]
    domains: ["mit.edu", "csail.mit.edu", "media.mit.edu"]
    keywords: ["Laboratory", "Department", "School of"]
    
  - name: "University of Toronto"
    aliases: ["UofT", "U of T", "Toronto University"]
    domains: ["utoronto.ca", "cs.toronto.edu"]
    keywords: ["Faculty", "Department", "Institute"]

industry:
  - name: "Google Research"
    aliases: ["Google", "Google AI", "Google Brain", "DeepMind"]
    domains: ["google.com", "deepmind.com"]
    keywords: ["Research", "Labs", "AI"]
    
  - name: "Microsoft Research"
    aliases: ["Microsoft", "MSR", "Microsoft AI"]
    domains: ["microsoft.com", "msr.com"]
    keywords: ["Research", "Labs", "Azure"]

government:
  - name: "National Research Council Canada"
    aliases: ["NRC", "CNRC"]
    domains: ["nrc-cnrc.gc.ca"]
    keywords: ["Government", "National", "Federal"]
```

### Validation and Testing
```python
@dataclass
class ValidationCase:
    affiliation: str
    expected_type: OrganizationType
    expected_org: str

class ClassifierValidator:
    def __init__(self, classifier: EnhancedOrganizationClassifier):
        self.classifier = classifier
        self.test_cases: List[ValidationCase] = []
    
    def load_test_cases(self, path: str) -> None:
        """Load validation test cases"""
        pass
    
    def validate_accuracy(self) -> Dict[str, float]:
        """Run validation and return accuracy metrics"""
        # Returns:
        # {
        #   "overall_accuracy": 0.92,
        #   "academic_precision": 0.94,
        #   "industry_precision": 0.89,
        #   "unknown_rate": 0.08
        # }
        pass
    
    def identify_failures(self) -> List[Tuple[ValidationCase, ClassificationResult]]:
        """Identify cases where classification failed"""
        pass
```

### Use Existing Infrastructure
```python
# Leverage existing components
from src.analysis.classification.organizations import load_organizations
from src.analysis.classification.validator import validate_classification

# Extend rather than replace
organizations = load_organizations()  # Load existing
organizations.update(enhanced_orgs)   # Add new ones
```

## Success Criteria
- [ ] Organization database expanded to 225+ institutions
- [ ] Classification accuracy >90% on test set
- [ ] Edge cases handled gracefully
- [ ] Industry threshold (25%) properly calibrated
- [ ] Fuzzy matching for name variations
- [ ] Confidence scores reliable
- [ ] Integration with existing classifier maintained

## Implementation Timeline
- Hour 1: Database expansion and YAML updates
- Hour 2: Parser enhancements and edge cases
- Hour 3: Validation suite and accuracy testing
