### ISSUE TITLE
M2-4: Extraction Process Design

### ISSUE THREAD

**Issue by bouthilx** [bouthilx/compute-forecast-framework#47]
# M2-4: Extraction Process Design

## Objective
Design systematic and reproducible extraction methodology for computational requirements from papers.

**Worker**: Analysis | **Effort**: S(2-3h) | **Domain**: Infrastructure

### Goals
1. Create step-by-step extraction protocol
2. Ensure reproducibility across analysts
3. Define quality control checkpoints
4. Integrate automated and manual methods

### 1. Extraction Protocol Document
```markdown
# Computational Requirements Extraction Protocol v1.0

## Phase 1: Paper Preparation (15 minutes)

### 1.1 Initial Assessment
- [ ] Verify paper has computational experiments
- [ ] Check PDF quality and readability
- [ ] Note paper structure (appendix, supplementary materials)

### 1.2 Quick Scan Locations
Priority order for finding computational details:
1. Abstract (for high-level claims)
2. Experimental Setup section
3. Implementation Details section
4. Appendix/Supplementary Materials
5. Tables with resource specifications
6. GitHub repository (if linked)

## Phase 2: Automated Extraction (10 minutes)

### 2.1 Run Computational Analyzer
```python
from src.analysis.computational.analyzer import ComputationalAnalyzer
analyzer = ComputationalAnalyzer()
results = analyzer.analyze(paper)
```

### 2.2 Review Automated Results
- Confidence score: _____ (record)
- Fields extracted: _____ (list)
- Missing critical fields: _____ (note)

### 3.1 Hardware Specifications
Search for keywords: GPU, TPU, CPU, cluster, node
- [ ] GPU Type: _________ (e.g., V100, A100)
- [ ] GPU Count: _________ 
- [ ] GPU Memory: _________ GB
- [ ] TPU Version: _________ (if applicable)
- [ ] Special hardware: _________

### 3.2 Training Time
Search for: hours, days, weeks, training time, wall clock
- [ ] Total training time: _________ 
- [ ] Unit: _________ (hours/days/weeks)
- [ ] Multiple runs?: _________ (yes/no)
- [ ] Pre-training time: _________ (if separate)

### 3.3 Model Scale
Search for: parameters, layers, dimensions, model size
- [ ] Total parameters: _________ 
- [ ] Architecture: _________ (e.g., Transformer)
- [ ] Special details: _________

### 3.4 Dataset Information
Search for: dataset, samples, tokens, size
- [ ] Dataset name: _________
- [ ] Dataset size: _________ (GB/samples/tokens)
- [ ] Batch size: _________
- [ ] Sequence length: _________ (if applicable)

### 3.5 Computational Cost
Calculate if not directly stated:
- [ ] Total GPU-hours: _________ (GPUs × time)
- [ ] Estimated cost: _________ (optional)

### 4.1 Consistency Checks
- [ ] GPU-hours calculation verified
- [ ] Model size plausible for architecture
- [ ] Training time reasonable for model size
- [ ] All units clearly specified

### 4.2 Uncertainty Assessment
Rate confidence for each field:
- Hardware: Low / Medium / High
- Training time: Low / Medium / High  
- Model scale: Low / Medium / High
- Overall: Low / Medium / High

### 5.1 Record Extraction
- Paper ID: _________
- Extraction timestamp: _________
- Analyst: _________
- Time spent: _________ minutes
- Confidence: _________

### 5.2 Notes Section
- Ambiguities: _________
- Assumptions made: _________
- Follow-up needed: _________
```

### 2. Extraction Decision Tree
```python
extraction_decision_tree = {
    "start": {
        "question": "Is computational info in abstract?",
        "yes": "Extract and verify in main text",
        "no": "Go to experimental section"
    },
    "experimental_section": {
        "question": "Found implementation details?",
        "yes": "Extract all available metrics",
        "no": "Check appendix"
    },
    "appendix": {
        "question": "Computational details in appendix?",
        "yes": "Extract comprehensively",
        "no": "Check for GitHub/code link"
    },
    "github": {
        "question": "Repository with config files?",
        "yes": "Extract from configuration",
        "no": "Mark as limited extraction"
    }
}
```

### 3. Quality Control Checklist
```markdown
## Extraction Quality Control

### Completeness Check
- [ ] All required fields attempted
- [ ] Missing fields explicitly noted
- [ ] Rationale for missing data documented

### Accuracy Verification
- [ ] Cross-referenced multiple sections
- [ ] Units clearly identified and consistent
- [ ] Calculations double-checked
- [ ] Outliers flagged for review

### Consistency Validation
- [ ] Compared with similar papers
- [ ] Verified against known constraints
- [ ] Temporal consistency (year vs. capability)

### Documentation Standards
- [ ] All assumptions recorded
- [ ] Confidence scores assigned
- [ ] Time tracking completed
- [ ] Review notes added
```

### 4. Standardized Extraction Form
```yaml
# extraction_form_template.yaml
metadata:
  paper_id: ""
  title: ""
  extraction_date: ""
  analyst: ""
  time_spent_minutes: 0
  
automated_extraction:
  confidence_score: 0.0
  fields_found: []
  fields_missing: []

hardware:
  gpu_type: ""
  gpu_count: null
  gpu_memory_gb: null
  tpu_version: ""
  tpu_cores: null
  nodes_used: null
  
training:
  total_time_hours: null
  time_unit_original: ""
  pre_training_hours: null
  fine_tuning_hours: null
  number_of_runs: 1
  
model:
  parameters_count: null
  parameters_unit: "millions"
  architecture: ""
  layers: null
  hidden_size: null
  
dataset:
  name: ""
  size_gb: null
  samples_count: null
  tokens_count: null
  batch_size: null
  
computation:
  total_gpu_hours: null
  calculation_method: ""
  estimated_cost_usd: null
  
validation:
  confidence_hardware: ""  # high/medium/low
  confidence_training: ""
  confidence_model: ""
  confidence_overall: ""
  
notes:
  ambiguities: []
  assumptions: []
  follow_up_needed: []
```

### 5. Common Patterns Guide
```markdown
## Common Extraction Patterns

### Pattern 1: Explicit Resource Statement
"We trained our model on 8 V100 GPUs for 5 days"
→ GPU: V100, Count: 8, Time: 120 hours, Total: 960 GPU-hours

### Pattern 2: Distributed Training
"32 nodes with 8 GPUs each for 36 hours"
→ GPU Count: 256, Time: 36 hours, Total: 9,216 GPU-hours

### Pattern 3: Multiple Training Phases
"Pre-training: 128 TPU cores for 2 weeks
Fine-tuning: 8 V100s for 3 days"
→ Record separately, sum for total

### Pattern 4: Implicit Information
"Following BERT-large configuration with standard training"
→ Parameters: 340M (from known architecture)
→ Training time: Estimate from similar papers

### Pattern 5: Cloud Credits
"Used $50,000 in cloud credits"
→ Estimate hours based on instance costs
→ Note as "cost-based estimate"
```

### 6. Edge Case Handling
```python
edge_case_procedures = {
    "missing_gpu_type": {
        "procedure": "Note GPU generation if mentioned (e.g., 'latest NVIDIA')",
        "assumption": "Use most common GPU for that year",
        "confidence": "medium"
    },
    "vague_time": {
        "example": "trained for several days",
        "procedure": "Use 3-5 days as range",
        "confidence": "low"
    },
    "distributed_training": {
        "procedure": "Calculate total GPU-hours across all nodes",
        "verification": "Check if paper reports total or per-node"
    },
    "multiple_experiments": {
        "procedure": "Extract largest single experiment",
        "note": "Document total if significantly different"
    }
}
```

### 7. Integration Workflow
```markdown
## Automated + Manual Integration

### Step 1: Automated First Pass
- Run computational analyzer
- Generate initial extraction
- Flag low-confidence fields

### Step 2: Manual Review
- Verify high-confidence fields
- Fill missing fields manually
- Resolve ambiguities

### Step 3: Validation
- Run consistency checks
- Compare with similar papers
- Flag outliers

### Step 4: Quality Review
- Senior analyst spot-check 10%
- Review all low-confidence extractions
- Update patterns guide with new cases

### Step 5: Database Entry
- Enter into standardized format
- Link source documents
- Version control updates
```

### 8. Training Materials
```markdown
## Analyst Training Guide

### Prerequisites
- Understanding of ML computational requirements
- Familiarity with GPU types and capabilities
- Basic understanding of scaling laws

### Training Exercises
1. Practice extraction on 5 example papers
2. Compare results with expert extractions
3. Review common mistakes

### Common Mistakes to Avoid
- Confusing GPU-hours with hours
- Missing distributed training multipliers
- Not checking supplementary materials
- Assuming single run when multiple reported

### Certification Process
- Complete 10 practice extractions
- Achieve 90% accuracy vs. expert
- Pass consistency test
```

## Implementation Timeline
- Hour 1: Protocol document creation
- Hour 2: Forms and templates design
- Hour 3: Edge case procedures and training materials
